/*
 * Copyright 2021 msgmonster project
 * 
 * Website: https://github.com/pinorobotics/msgmonster
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Java class for jrosclient
 * 
 * Generated for ROS file: std_srvs/SetBoolServiceResponse
 */

package ue00.srv;

import java.util.Objects;

import id.jrosmessages.Message;
import id.jrosmessages.MessageMetadata;
import id.jrosmessages.Array;
import id.xfunction.XJson;
import id.xfunction.Preconditions;

import id.jrosmessages.RosInterfaceType;
import id.jrosmessages.std_msgs.StringMessage;

/**
 * Definition for std_srvs/SetBoolServiceResponse
 */
@MessageMetadata(
    name = SetBoolResponseMessage.NAME,
    interfaceType = RosInterfaceType.SERVICE,
    fields = { "success", "message" }
)
public class SetBoolResponseMessage implements Message {
   
   static final String NAME = "std_srvs/SetBoolServiceResponse";

   /**
    * indicate successful run of triggered service
    */
   public boolean success;
   
   /**
    * informational, e.g. for error messages
    */
   public StringMessage message = new StringMessage();
   
   public SetBoolResponseMessage withSuccess(boolean success) {
       this.success = success;
       return this;
   }
   
   public SetBoolResponseMessage withMessage(StringMessage message) {
       this.message = message;
       return this;
   }
   
   @Override
   public int hashCode() {
       return Objects.hash(
           success,
           message
       );
   }
   
   @Override
   public boolean equals(Object obj) {
       if (obj instanceof SetBoolResponseMessage other)
           return
               success == other.success &&
               Objects.equals(message, other.message)
           ;
       return false;
   }
   
   @Override
   public String toString() {
       return XJson.asString(
           "success", success,
           "message", message
       );
   }
   
}
