/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ue07;

/**
 *
 * @author robu
 */
public class QuaderGui extends javax.swing.JFrame
{

  /**
   * Creates new form QuaderGui
   */
  public QuaderGui()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane1 = new javax.swing.JScrollPane();
    pMain = new javax.swing.JPanel();
    pSouth = new javax.swing.JPanel();
    pButtons = new javax.swing.JPanel();
    btBerechnen = new javax.swing.JButton();
    btLoeschen = new javax.swing.JButton();
    btBeenden = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Quader Gui");
    setLocationByPlatform(true);

    pMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
    pMain.setLayout(new java.awt.BorderLayout());

    pSouth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

    pButtons.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

    btBerechnen.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    btBerechnen.setText("Berechnen");
    pButtons.add(btBerechnen);

    btLoeschen.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    btLoeschen.setText("Löschen");
    pButtons.add(btLoeschen);

    btBeenden.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    btBeenden.setText("App beenden");
    pButtons.add(btBeenden);

    pSouth.add(pButtons);

    pMain.add(pSouth, java.awt.BorderLayout.PAGE_END);

    jScrollPane1.setViewportView(pMain);

    getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(QuaderGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(QuaderGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(QuaderGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(QuaderGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new QuaderGui().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btBeenden;
  private javax.swing.JButton btBerechnen;
  private javax.swing.JButton btLoeschen;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JPanel pButtons;
  private javax.swing.JPanel pMain;
  private javax.swing.JPanel pSouth;
  // End of variables declaration//GEN-END:variables
}
