
package ue05;

/**
 *
 * @author robu
 */
public class MeinErstesJavaSwingFenster extends javax.swing.JFrame 
{

  /**
   * Creates new form MeinErstesJavaSwingFenster
   */
  public MeinErstesJavaSwingFenster()
  {
    initComponents();
    
    final String titel = getTitle();    //Sachen zum Titel zu des Fensters hinzufügen
    setTitle("*** " + titel + " ***");
    
    //setLocationRelativeTo(null);  //setzt das Fenster in die Mitte des Monitors
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    lbText = new javax.swing.JLabel();
    tfEingabe = new javax.swing.JTextField();
    btBerechnen = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Supa JAva Ui Programm");
    setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    setLocation(new java.awt.Point(0, 0));
    setLocationByPlatform(true);

    lbText.setFont(new java.awt.Font("Nimbus Roman", 0, 24)); // NOI18N
    lbText.setText("Das ist ein schöner Text");
    lbText.setToolTipText("");
    getContentPane().add(lbText, java.awt.BorderLayout.CENTER);

    tfEingabe.setFont(new java.awt.Font("Nimbus Roman", 0, 24)); // NOI18N
    tfEingabe.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        tfEingabeActionPerformed(evt);
      }
    });
    getContentPane().add(tfEingabe, java.awt.BorderLayout.PAGE_START);

    btBerechnen.setFont(new java.awt.Font("Nimbus Roman", 0, 24)); // NOI18N
    btBerechnen.setText("Berechnen");
    btBerechnen.setToolTipText("");
    getContentPane().add(btBerechnen, java.awt.BorderLayout.PAGE_END);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void tfEingabeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_tfEingabeActionPerformed
  {//GEN-HEADEREND:event_tfEingabeActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_tfEingabeActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(MeinErstesJavaSwingFenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(MeinErstesJavaSwingFenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(MeinErstesJavaSwingFenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(MeinErstesJavaSwingFenster.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new MeinErstesJavaSwingFenster().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btBerechnen;
  private javax.swing.JLabel lbText;
  private javax.swing.JTextField tfEingabe;
  // End of variables declaration//GEN-END:variables
}

