/*
 * Copyright 2021 msgmonster project
 * 
 * Website: https://github.com/pinorobotics/msgmonster
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Java class for jrosclient
 * 
 * Generated for ROS file: ledctrl_interfaces/CameraCmd
 */

package ue02.ros.srv;

import id.jrosmessages.MessageDescriptor;
import pinorobotics.jrosservices.msgs.ServiceDefinition;

/**
 * Definition for ledctrl_interfaces/srv/CameraCmd
 * 
 * ./msgmonster ros2 srv ledctrl_interfaces/srv/CameraCmd /home/robu/work/java/uebungen/src/robotik_ros2/ue_jros2_robotctrl/ue01/srv/
 */
public class CameraCmdServiceDefinition
        implements ServiceDefinition<CameraCmdRequestMessage, CameraCmdResponseMessage> {
    private static final MessageDescriptor<CameraCmdRequestMessage> REQUEST_MESSAGE_DESCRIPTOR =
            new MessageDescriptor<>(CameraCmdRequestMessage.class);
    private static final MessageDescriptor<CameraCmdResponseMessage> RESPONSE_MESSAGE_DESCRIPTOR =
            new MessageDescriptor<>(CameraCmdResponseMessage.class);

    @Override
    public MessageDescriptor<CameraCmdRequestMessage> getServiceRequestMessage() {
        return REQUEST_MESSAGE_DESCRIPTOR;
    }

    @Override
    public MessageDescriptor<CameraCmdResponseMessage> getServiceResponseMessage() {
        return RESPONSE_MESSAGE_DESCRIPTOR;
    }
}
