/*
 * Copyright 2021 msgmonster project
 * 
 * Website: https://github.com/pinorobotics/msgmonster
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Java class for jrosclient
 * 
 * Generated for ROS file: std_srvs/SetBoolServiceRequest
 */

package ue00.srv;

import java.util.Objects;

import id.jrosmessages.Message;
import id.jrosmessages.MessageMetadata;
import id.jrosmessages.Array;
import id.xfunction.XJson;
import id.xfunction.Preconditions;

import id.jrosmessages.RosInterfaceType;

/**
 * Definition for std_srvs/SetBoolServiceRequest
 */
@MessageMetadata(
    name = SetBoolRequestMessage.NAME,
    interfaceType = RosInterfaceType.SERVICE
)
public class SetBoolRequestMessage implements Message {
   
   static final String NAME = "std_srvs/SetBoolServiceRequest";

   /**
    * e.g. for hardware enabling / disabling
    */
   public boolean data;
   
   public SetBoolRequestMessage withData(boolean data) {
       this.data = data;
       return this;
   }
   
   @Override
   public int hashCode() {
       return Objects.hash(
           data
       );
   }
   
   @Override
   public boolean equals(Object obj) {
       if (obj instanceof SetBoolRequestMessage other)
           return
               data == other.data
           ;
       return false;
   }
   
   @Override
   public String toString() {
       return XJson.asString(
           "data", data
       );
   }
   
}
