/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ue06;

import java.util.NoSuchElementException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import ue01.SpritRechner;

/**
 *
 * @author robu
 */
public class SpritGUI extends javax.swing.JFrame
{

  /**
   * Creates new form SpritGUI
   */
  public SpritGUI()
  {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {

    jScrollPane2 = new javax.swing.JScrollPane();
    pMain = new javax.swing.JPanel();
    jButton1 = new javax.swing.JButton();
    pContent = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    tfKm = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    tfL = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    tfDurchschnitt = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Spritrechner");
    setAutoRequestFocus(false);
    setLocationByPlatform(true);

    pMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
    pMain.setLayout(new java.awt.BorderLayout(0, 8));

    jButton1.setFont(new java.awt.Font("DejaVu Sans", 1, 24)); // NOI18N
    jButton1.setText("Berechnen");
    jButton1.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onBerechnen(evt);
      }
    });
    pMain.add(jButton1, java.awt.BorderLayout.SOUTH);

    pContent.setLayout(new java.awt.GridLayout(0, 2, 4, 4));

    jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    jLabel1.setText("Gefahrene km");
    pContent.add(jLabel1);

    tfKm.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    pContent.add(tfKm);

    jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    jLabel2.setText("Verbrauch in l");
    pContent.add(jLabel2);

    tfL.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    pContent.add(tfL);

    jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    jLabel3.setText("Durchschnittsverbrauch");
    pContent.add(jLabel3);

    tfDurchschnitt.setEditable(false);
    tfDurchschnitt.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    pContent.add(tfDurchschnitt);

    pMain.add(pContent, java.awt.BorderLayout.CENTER);

    jScrollPane2.setViewportView(pMain);

    getContentPane().add(jScrollPane2, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void onBerechnen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onBerechnen
  {//GEN-HEADEREND:event_onBerechnen
    //Auslesen der eingangsgrößen aus den textfeldern -> string
    //strings umwandeln in double
    //rechenen mit rechnerklasse
    //ergebniss ist der datentyp double-> umwandeln in string
    //ausgeben
    
    
    try { //Handlermethode darf keine Exceptions werfen !!!
      //Eingangsgrößen aus Textfeldern einlesen und in Zahlen umwandeln
      
      /*
      final String sKm = tfKm.getText();
      final Scanner scanner = new Scanner(sKm);
      final double km = scanner.nextDouble();
      */
      final double 
        km = new Scanner(tfKm.getText()).nextDouble(),
        liter = new Scanner(tfL.getText()).nextDouble(),
      
      //Rechnen
        Durchschnitt = new SpritRechner(km, liter).getDurchschnittsverbrauch();
      
      //Ergebnis in String umwandeln und in Textfeld ausgeben
      tfDurchschnitt.setText(String.format("%.2f", Durchschnitt));
      
    }
    catch(NoSuchElementException ex) {
      JOptionPane.showMessageDialog(this, "Falsches Zahlenformat",
              "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
    }
    catch(Exception ex) {
      // ex.printStackTrace();
      JOptionPane.showMessageDialog(this, ex.getMessage(),
          "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_onBerechnen

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(SpritGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(SpritGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(SpritGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(SpritGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new SpritGUI().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JPanel pContent;
  private javax.swing.JPanel pMain;
  private javax.swing.JTextField tfDurchschnitt;
  private javax.swing.JTextField tfKm;
  private javax.swing.JTextField tfL;
  // End of variables declaration//GEN-END:variables
}
