/*
 * Copyright 2021 msgmonster project
 * 
 * Website: https://github.com/pinorobotics/msgmonster
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Java class for jrosclient
 * 
 * Generated for ROS file: demo_interfaces/DemoMotor

./msgmonster ros2 srv demo_interfaces/srv/DemoMotor /home/robu/work/java/uebungen/src/ue02/demo_java_python_ws/src/demo_java/srv/
 */

package ue00.srv;

import id.jrosmessages.MessageDescriptor;
import pinorobotics.jrosservices.msgs.ServiceDefinition;

/**
 * Definition for demo_interfaces/srv/DemoMotor
 */
public class DemoMotorServiceDefinition
        implements ServiceDefinition<DemoMotorRequestMessage, DemoMotorResponseMessage> {
    private static final MessageDescriptor<DemoMotorRequestMessage> REQUEST_MESSAGE_DESCRIPTOR =
            new MessageDescriptor<>(DemoMotorRequestMessage.class);
    private static final MessageDescriptor<DemoMotorResponseMessage> RESPONSE_MESSAGE_DESCRIPTOR =
            new MessageDescriptor<>(DemoMotorResponseMessage.class);

    @Override
    public MessageDescriptor<DemoMotorRequestMessage> getServiceRequestMessage() {
        return REQUEST_MESSAGE_DESCRIPTOR;
    }

    @Override
    public MessageDescriptor<DemoMotorResponseMessage> getServiceResponseMessage() {
        return RESPONSE_MESSAGE_DESCRIPTOR;
    }
}
