/*
 * Copyright 2021 msgmonster project
 * 
 * Website: https://github.com/pinorobotics/msgmonster
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Java class for jrosclient
 * 
 * Generated for ROS file: ledctrl_interfaces/BacklightValueServiceRequest
 */

package ue01.srv;

import java.util.Objects;

import id.jrosmessages.Message;
import id.jrosmessages.MessageMetadata;
import id.jrosmessages.Array;
import id.xfunction.XJson;
import id.xfunction.Preconditions;

import id.jrosmessages.RosInterfaceType;

/**
 * Definition for ledctrl_interfaces/BacklightValueServiceRequest
 */
@MessageMetadata(
    name = BacklightValueRequestMessage.NAME,
    interfaceType = RosInterfaceType.SERVICE,
    fields = { "side", "brightness_percent" }
)
public class BacklightValueRequestMessage implements Message {
   
   static final String NAME = "ledctrl_interfaces/BacklightValueServiceRequest";

   public byte side;
   
   public byte brightness_percent;
   
   public BacklightValueRequestMessage withSide(byte side) {
       this.side = side;
       return this;
   }
   
   public BacklightValueRequestMessage withBrightnessPercent(byte brightness_percent) {
       this.brightness_percent = brightness_percent;
       return this;
   }
   
   @Override
   public int hashCode() {
       return Objects.hash(
           side,
           brightness_percent
       );
   }
   
   @Override
   public boolean equals(Object obj) {
       if (obj instanceof BacklightValueRequestMessage other)
           return
               side == other.side &&
               brightness_percent == other.brightness_percent
           ;
       return false;
   }
   
   @Override
   public String toString() {
       return XJson.asString(
           "side", side,
           "brightness_percent", brightness_percent
       );
   }
   
}
