/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ue01.gui;

import ue01.data.RobotCtrlROS;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author robu
 */
public class RobotCtrlGUI extends javax.swing.JFrame
{

    private final RobotCtrlROS nodeRobotCtrl = new RobotCtrlROS();
    
    /**
     * Creates new form RobotCtrlGUI
     */
    public RobotCtrlGUI()
    {
        initComponents();
        
        setSize(800, 480);
        setResizable(false);
        setLocationRelativeTo(null);
        System.out.println(getClass().getSimpleName() + " Größe: " + getSize().width + " x " + getSize().height);
        System.out.println("RMW_IMPLEMENTATION = " + System.getenv("RMW_IMPLEMENTATION"));
    }

    /**bu 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        tpRobotCtrl = new javax.swing.JTabbedPane();
        pTechTitans = new javax.swing.JPanel();
        lblTechTitans = new javax.swing.JLabel();
        lblHTL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 480));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                onWindowClosing(evt);
            }
        });

        tpRobotCtrl.setToolTipText("");
        tpRobotCtrl.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tpRobotCtrl.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        tpRobotCtrl.setOpaque(true);

        pTechTitans.setLayout(new java.awt.GridLayout(1, 2));

        lblTechTitans.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTechTitans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue01/icons/TechTitans_small.png"))); // NOI18N
        pTechTitans.add(lblTechTitans);

        lblHTL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHTL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue01/icons/HTL_Kaindorf_Logo.png"))); // NOI18N
        pTechTitans.add(lblHTL);

        tpRobotCtrl.addTab("About", pTechTitans);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tpRobotCtrl, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(tpRobotCtrl, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    public void closeGUI()
    {
      if(JOptionPane.showConfirmDialog(this, 
        "Wirklich beenden?", "Sicherheitsabfrage", 
        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
      {
        nodeRobotCtrl.shutdown();
        dispose();
        System.exit(0); //Notwendig wenn keine Daemon-Threads laufen. Daemon Threads werden automatisch gestoppt!
      }
    }
    
    private void onWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_onWindowClosing
    {//GEN-HEADEREND:event_onWindowClosing
        closeGUI();
    }//GEN-LAST:event_onWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(RobotCtrlGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(RobotCtrlGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(RobotCtrlGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(RobotCtrlGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new RobotCtrlGUI().setVisible(true);
            }
        });
    }

    public RobotCtrlROS getNodeRobotCtrl()
    {
        return nodeRobotCtrl;
    }

    public JTabbedPane getTabbedPane()
    {
        return tpRobotCtrl;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lblHTL;
    private javax.swing.JLabel lblTechTitans;
    private javax.swing.JPanel pTechTitans;
    private javax.swing.JTabbedPane tpRobotCtrl;
    // End of variables declaration//GEN-END:variables
}
