/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ue02.gui;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

import ue01.data.RobotCtrlROS;
import ue01.gui.RobotCtrlGUI;
import ue02.data.LEDConfig;
import ue02.ros.data.LEDCtrlROS;

/**
 *
 * @author robot
 */
public class LEDCtrlPanel extends javax.swing.JPanel {
    
    private final LEDConfig leds = new LEDConfig();
    private final LEDDataTableModel tableLEDDataModel = new LEDDataTableModel(leds.getLEDs());
    private final RobotCtrlGUI parent;
    private final LEDCtrlROS rosLEDCtrl;

    /**
     * Creates new form LEDCtrlGui
     */
    public LEDCtrlPanel(RobotCtrlGUI parent, RobotCtrlROS nodeRobotCtrl) {
        
        this.parent = parent;
        this.rosLEDCtrl = new LEDCtrlROS(nodeRobotCtrl);
        
        initComponents();
        
        btnDelete.setEnabled(false);
                
        this.tblLedColor.setModel(tableLEDDataModel); 
        
        tblLedColor.getSelectionModel().addListSelectionListener(e -> {
            boolean selected = tblLedColor.getSelectedRow() != -1;
            btnDelete.setEnabled(selected);
        });
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pCenter = new javax.swing.JPanel();
        pColor = new javax.swing.JPanel();
        pTurnService = new javax.swing.JPanel();
        btTurnLeft = new javax.swing.JButton();
        btTurnRight = new javax.swing.JButton();
        btDetectLeft = new javax.swing.JButton();
        btDetectRight = new javax.swing.JButton();
        pColorTable = new javax.swing.JPanel();
        spColorTable = new javax.swing.JScrollPane();
        tblLedColor = new javax.swing.JTable();
        pSouth = new javax.swing.JPanel();
        btnLoad = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPublish = new javax.swing.JButton();
        btnReadColors = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout(5, 5));

        pCenter.setLayout(new java.awt.BorderLayout());

        pColor.setLayout(new java.awt.BorderLayout());

        pTurnService.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "ROS2-Services"));
        pTurnService.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btTurnLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/turn-left_48x48.png"))); // NOI18N
        btTurnLeft.setMaximumSize(new java.awt.Dimension(54, 54));
        btTurnLeft.setMinimumSize(new java.awt.Dimension(54, 54));
        btTurnLeft.setPreferredSize(new java.awt.Dimension(54, 54));
        btTurnLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTurnLeft(evt);
            }
        });
        pTurnService.add(btTurnLeft);

        btTurnRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/turn-right_48x48.png"))); // NOI18N
        btTurnRight.setMaximumSize(new java.awt.Dimension(54, 54));
        btTurnRight.setMinimumSize(new java.awt.Dimension(54, 54));
        btTurnRight.setPreferredSize(new java.awt.Dimension(54, 54));
        btTurnRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onTurnRight(evt);
            }
        });
        pTurnService.add(btTurnRight);

        btDetectLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/detect_left_48x48.png"))); // NOI18N
        btDetectLeft.setMaximumSize(new java.awt.Dimension(54, 54));
        btDetectLeft.setMinimumSize(new java.awt.Dimension(54, 54));
        btDetectLeft.setPreferredSize(new java.awt.Dimension(54, 54));
        btDetectLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDetectLeft(evt);
            }
        });
        pTurnService.add(btDetectLeft);

        btDetectRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/detect_right_48x48.png"))); // NOI18N
        btDetectRight.setMaximumSize(new java.awt.Dimension(54, 54));
        btDetectRight.setMinimumSize(new java.awt.Dimension(54, 54));
        btDetectRight.setPreferredSize(new java.awt.Dimension(54, 54));
        btDetectRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onDetectRight(evt);
            }
        });
        pTurnService.add(btDetectRight);

        pColor.add(pTurnService, java.awt.BorderLayout.SOUTH);

        pColorTable.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Farbwerte für Publisher"));
        pColorTable.setAutoscrolls(true);

        tblLedColor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        spColorTable.setViewportView(tblLedColor);

        javax.swing.GroupLayout pColorTableLayout = new javax.swing.GroupLayout(pColorTable);
        pColorTable.setLayout(pColorTableLayout);
        pColorTableLayout.setHorizontalGroup(
            pColorTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pColorTableLayout.createSequentialGroup()
                .addGap(0, 7, Short.MAX_VALUE)
                .addComponent(spColorTable, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 7, Short.MAX_VALUE))
        );
        pColorTableLayout.setVerticalGroup(
            pColorTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pColorTableLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spColorTable, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pColor.add(pColorTable, java.awt.BorderLayout.CENTER);

        pCenter.add(pColor, java.awt.BorderLayout.CENTER);

        add(pCenter, java.awt.BorderLayout.CENTER);

        pSouth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/load_48x48.png"))); // NOI18N
        btnLoad.setMaximumSize(new java.awt.Dimension(54, 54));
        btnLoad.setMinimumSize(new java.awt.Dimension(54, 54));
        btnLoad.setPreferredSize(new java.awt.Dimension(54, 54));
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnLoad(evt);
            }
        });
        pSouth.add(btnLoad);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/save_48x48.png"))); // NOI18N
        btnSave.setMaximumSize(new java.awt.Dimension(54, 54));
        btnSave.setMinimumSize(new java.awt.Dimension(54, 54));
        btnSave.setPreferredSize(new java.awt.Dimension(54, 54));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOnSave(evt);
            }
        });
        pSouth.add(btnSave);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/plus_48x48.png"))); // NOI18N
        btnAdd.setMaximumSize(new java.awt.Dimension(54, 54));
        btnAdd.setMinimumSize(new java.awt.Dimension(54, 54));
        btnAdd.setPreferredSize(new java.awt.Dimension(54, 54));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAdd(evt);
            }
        });
        pSouth.add(btnAdd);

        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/bin_48x48.png"))); // NOI18N
        btnDelete.setMaximumSize(new java.awt.Dimension(54, 54));
        btnDelete.setMinimumSize(new java.awt.Dimension(54, 54));
        btnDelete.setPreferredSize(new java.awt.Dimension(54, 54));
        pSouth.add(btnDelete);

        btnPublish.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/write-bot_48x48.png"))); // NOI18N
        btnPublish.setMaximumSize(new java.awt.Dimension(54, 54));
        btnPublish.setMinimumSize(new java.awt.Dimension(54, 54));
        btnPublish.setPreferredSize(new java.awt.Dimension(54, 54));
        btnPublish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onPublish(evt);
            }
        });
        pSouth.add(btnPublish);

        btnReadColors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/read-bot_48x48.png"))); // NOI18N
        btnReadColors.setMaximumSize(new java.awt.Dimension(54, 54));
        btnReadColors.setMinimumSize(new java.awt.Dimension(54, 54));
        btnReadColors.setPreferredSize(new java.awt.Dimension(54, 54));
        btnReadColors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onReadColors(evt);
            }
        });
        pSouth.add(btnReadColors);

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/logout_48x48.png"))); // NOI18N
        btnClose.setMaximumSize(new java.awt.Dimension(54, 54));
        btnClose.setMinimumSize(new java.awt.Dimension(54, 54));
        btnClose.setPreferredSize(new java.awt.Dimension(54, 54));
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onClose(evt);
            }
        });
        pSouth.add(btnClose);

        add(pSouth, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void onClose(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onClose
       this.parent.closeGUI();
    }//GEN-LAST:event_onClose

    private void onTurnLeft(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTurnLeft
        // Startet einen neuen Thread im Hintergrund und ruft dort das Service auf
        // Die GUI wird dadurch nicht blockiert
        new Thread(() -> this.rosLEDCtrl.callLeftTurnSignal()).start();
    }//GEN-LAST:event_onTurnLeft

    private void onTurnRight(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onTurnRight
       new Thread(() -> this.rosLEDCtrl.callRightTurnSignal()).start();
    }//GEN-LAST:event_onTurnRight

    private void onDetectLeft(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDetectLeft
        new Thread(() -> this.rosLEDCtrl.callLeftDetectSignal()).start();
    }//GEN-LAST:event_onDetectLeft

    private void onDetectRight(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onDetectRight
       new Thread(() -> this.rosLEDCtrl.callRightDetectSignal()).start();
    }//GEN-LAST:event_onDetectRight

    private void onPublish(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onPublish
       this.rosLEDCtrl.publishLEDData(tableLEDDataModel.getLEDDataList());
    }//GEN-LAST:event_onPublish

    private void onReadColors(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onReadColors
        byte[] led_config = rosLEDCtrl.callReadColors();
        
        try {
            leds.readFrom(led_config);
        } catch (Exception ex) {
            Logger.getLogger(LEDCtrlPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableLEDDataModel.fireTableDataChanged(); //Table aktualisieren
    }//GEN-LAST:event_onReadColors

    private void btnOnLoad(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnLoad
        final JFileChooser chooser = new JFileChooser();
        chooser.addChoosableFileFilter(
            new FileNameExtensionFilter("LED-Config-Datein","csv","txt"));
        chooser.setAcceptAllFileFilterUsed(false);
        
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            final File file = chooser.getSelectedFile();
            
            try (
                final BufferedReader reader =
                  new BufferedReader(
                  new InputStreamReader(
                  new FileInputStream(file), "utf8"));
            )
            {
                leds.readFrom(reader);
                tableLEDDataModel.fireTableDataChanged();
            } catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Fehler aufgetreten. Laden der Datei fehlgeschlagen", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnOnLoad

    private void btnOnSave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOnSave
        final JFileChooser chooser = new JFileChooser();
        
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            final String path = file.getAbsolutePath();
            
            if(! path.toLowerCase().endsWith(".csv")) {
                file = new File(path+".csv");
            }
            
            try (
                final BufferedWriter writer = new BufferedWriter(
                    new OutputStreamWriter(
                    new FileOutputStream(file), "utf8"))        
            )
            {
                leds.writeTo(writer);
                JOptionPane.showMessageDialog(this, 
                        String.format("%d LEDs erfolgreich gespeichert!", 
                                leds.size()), "Erfolgreich gespeichert", 
                                JOptionPane.ERROR_MESSAGE);
            } 
            catch (Exception ex) {
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this, 
                        ex.getMessage(), "Fehler aufgetreten.", 
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnOnSave

    private void onAdd(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAdd
        // TODO add your handling code here:
    }//GEN-LAST:event_onAdd


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btDetectLeft;
    private javax.swing.JButton btDetectRight;
    private javax.swing.JButton btTurnLeft;
    private javax.swing.JButton btTurnRight;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnPublish;
    private javax.swing.JButton btnReadColors;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pColor;
    private javax.swing.JPanel pColorTable;
    private javax.swing.JPanel pSouth;
    private javax.swing.JPanel pTurnService;
    private javax.swing.JScrollPane spColorTable;
    private javax.swing.JTable tblLedColor;
    // End of variables declaration//GEN-END:variables
}
