package ue02.gui;

import java.awt.Color;
import javax.swing.JOptionPane;
import ue02.data.LEDData;

/**
 *
 * @author robot
 */
public class LEDDataDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LEDDataDialog.class.getName());
    
    private LEDData ledData = null;
    private boolean pressedOk = false;
    /**
     * Creates new form LEDDataDialog
     */
    public LEDDataDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal); //super => Ruft Elternklasse auf (parent=hauptgui; modal=das vorige Fenster reagiert nicht mehr)
        initComponents();
        
        setSize(800, 480);
        setResizable(false);
        setLocationRelativeTo(getParent());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pMain = new javax.swing.JPanel();
        pColor = new javax.swing.JPanel();
        lblLEdPos = new javax.swing.JLabel();
        spLEDPos = new javax.swing.JSpinner();
        cchLEDColor = new javax.swing.JColorChooser();
        slWhiteColor = new javax.swing.JSlider();
        lblLEDW = new javax.swing.JLabel();
        pSouth = new javax.swing.JPanel();
        btnApply = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        pMain.setLayout(new java.awt.BorderLayout());

        java.awt.GridBagLayout pColorLayout = new java.awt.GridBagLayout();
        pColorLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0};
        pColorLayout.rowHeights = new int[] {0, 5, 0, 5, 0};
        pColor.setLayout(pColorLayout);

        lblLEdPos.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblLEdPos.setText("Led Position:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pColor.add(lblLEdPos, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pColor.add(spLEDPos, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        pColor.add(cchLEDColor, gridBagConstraints);

        slWhiteColor.setMajorTickSpacing(10);
        slWhiteColor.setMaximum(255);
        slWhiteColor.setPaintLabels(true);
        slWhiteColor.setPaintTicks(true);
        slWhiteColor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        slWhiteColor.setDoubleBuffered(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pColor.add(slWhiteColor, gridBagConstraints);

        lblLEDW.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        lblLEDW.setText("Hellichkeit der W-LED");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pColor.add(lblLEDW, gridBagConstraints);

        pMain.add(pColor, java.awt.BorderLayout.CENTER);

        pSouth.setLayout(new java.awt.GridLayout(1, 2, 8, 8));

        btnApply.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnApply.setText("Apply");
        btnApply.setPreferredSize(new java.awt.Dimension(110, 40));
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onApply(evt);
            }
        });
        pSouth.add(btnApply);

        btnCancel.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(110, 40));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onCancel(evt);
            }
        });
        pSouth.add(btnCancel);

        pMain.add(pSouth, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onApply(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onApply

        try {
            int pos = (Integer) spLEDPos.getValue();
            Color color = cchLEDColor.getColor();

            int r = color.getRed();
            int g = color.getGreen();
            int b = color.getBlue();
            int w = slWhiteColor.getValue();

            ledData = new LEDData(pos,  r, g, b, w);
            pressedOk = true;
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), 
                    "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
        }                        
    }//GEN-LAST:event_onApply

    private void onCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onCancel
        dispose();
    }//GEN-LAST:event_onCancel

    public LEDData getLedData() {
        return ledData;
    }

    public boolean setLedData(LEDData ledData) {
        spLEDPos.setValue(ledData.getPosition());
        slWhiteColor.setValue(ledData.getW());
        
        Color color = new Color(ledData.getR(), ledData.getG(), ledData.getB());
        cchLEDColor.setColor(color);
        
        return true;
    }

    public boolean pressedOK() {
        return pressedOk;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                LEDDataDialog dialog = new LEDDataDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.JColorChooser cchLEDColor;
    private javax.swing.JLabel lblLEDW;
    private javax.swing.JLabel lblLEdPos;
    private javax.swing.JPanel pColor;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pSouth;
    private javax.swing.JSlider slWhiteColor;
    private javax.swing.JSpinner spLEDPos;
    // End of variables declaration//GEN-END:variables
}
