package ue10a.gui;

import ue10a.gui.*;
import ue10a.calc.PerfekteZahlenRechnerVersion2;
import java.util.*;
import java.util.concurrent.ExecutionException;
import javax.swing.*;
import ue10a.data.PerfekteZahl;

/**
 *
 * @author werner
 */
public class PerfekteZahlenGuiVerion2 extends javax.swing.JFrame
{

  /**
   * Creates new form PerfekteZahlenGui
   */
  public PerfekteZahlenGuiVerion2()
  {
    initComponents();
    listenfeld.setModel(new PerfekteZahlListModel(new ArrayList<>()));
    pack();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pMain = new javax.swing.JPanel();
        pWest = new javax.swing.JPanel();
        pEinAus = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spUntergrenze = new javax.swing.JSpinner();
        spObergrenze = new javax.swing.JSpinner();
        tfAnzahl = new javax.swing.JFormattedTextField();
        tfRechenzeit = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        pBefehle = new javax.swing.JPanel();
        btBerechnen = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btLoeschen = new javax.swing.JButton();
        btBeenden = new javax.swing.JButton();
        pListenfeld = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listenfeld = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Perfekte Zahlen V 0.1");
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowClosing(evt);
            }
        });

        pMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pMain.setLayout(new java.awt.BorderLayout(8, 8));

        pWest.setLayout(new java.awt.BorderLayout(0, 8));

        pEinAus.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Ein-/Ausgabe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)));
        java.awt.GridBagLayout pEinAUsLayout = new java.awt.GridBagLayout();
        pEinAUsLayout.columnWidths = new int[] {0, 4, 0, 4, 0};
        pEinAUsLayout.rowHeights = new int[] {0, 4, 0, 4, 0, 4, 0, 4, 0};
        pEinAus.setLayout(pEinAUsLayout);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel1.setText("Untergrenze");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pEinAus.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel2.setText("Obergrenze");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pEinAus.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel3.setText("Anzahl");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pEinAus.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel4.setText("Rechenzeit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pEinAus.add(jLabel4, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        jLabel5.setText("ms");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pEinAus.add(jLabel5, gridBagConstraints);

        spUntergrenze.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        spUntergrenze.setModel(new javax.swing.SpinnerNumberModel(2, 2, 999999, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pEinAus.add(spUntergrenze, gridBagConstraints);

        spObergrenze.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        spObergrenze.setModel(new javax.swing.SpinnerNumberModel(999, 2, 999999, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pEinAus.add(spObergrenze, gridBagConstraints);

        tfAnzahl.setColumns(8);
        tfAnzahl.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pEinAus.add(tfAnzahl, gridBagConstraints);

        tfRechenzeit.setColumns(8);
        tfRechenzeit.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        pEinAus.add(tfRechenzeit, gridBagConstraints);

        jSeparator1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 8, 0);
        pEinAus.add(jSeparator1, gridBagConstraints);

        pWest.add(pEinAus, java.awt.BorderLayout.NORTH);

        pBefehle.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Befehle", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)));
        pBefehle.setLayout(new java.awt.GridLayout(0, 1, 0, 8));

        btBerechnen.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btBerechnen.setText("Berechnen");
        btBerechnen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBerechnen(evt);
            }
        });
        pBefehle.add(btBerechnen);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        btLoeschen.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btLoeschen.setText("Löschen");
        btLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLoeschen(evt);
            }
        });
        jPanel1.add(btLoeschen);

        btBeenden.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        btBeenden.setText("Beenden");
        btBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBeenden(evt);
            }
        });
        jPanel1.add(btBeenden);

        pBefehle.add(jPanel1);

        pWest.add(pBefehle, java.awt.BorderLayout.SOUTH);

        pMain.add(pWest, java.awt.BorderLayout.LINE_START);

        pListenfeld.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Perfekte Zahlen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)));
        pListenfeld.setLayout(new java.awt.BorderLayout());

        listenfeld.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(listenfeld);

        pListenfeld.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pMain.add(pListenfeld, java.awt.BorderLayout.CENTER);

        getContentPane().add(pMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private final class PerfekteZahlenWorker extends SwingWorker<PerfekteZahlenRechnerVersion2, Object>
  {
    private final int untergrenze, obergrenze;
    public PerfekteZahlenWorker(int untergrenze, int obergrenze)
    {
      this.untergrenze = untergrenze;
      this.obergrenze = obergrenze;
    }
    @Override
    protected PerfekteZahlenRechnerVersion2 doInBackground() throws Exception
    {
      return new PerfekteZahlenRechnerVersion2(untergrenze, obergrenze);
    }
    @Override
    protected void done()
    {
      try
      {
        final PerfekteZahlenRechnerVersion2 rechner = get();
        final List<PerfekteZahl> perfekteZahlen = rechner.getPerfekteZahlen();
        tfAnzahl.setValue(perfekteZahlen.size());
        tfRechenzeit.setValue(rechner.getMillis());
        listenfeld.setModel(new PerfekteZahlListModel(perfekteZahlen));
        pack();
      }
      catch (InterruptedException ignore) { }
      catch (ExecutionException ex)
      {
        JOptionPane.showMessageDialog(PerfekteZahlenGuiVerion2.this,
          ex.getCause().getMessage(),
          "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
      }
    }
  }
  
  private void onBerechnen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onBerechnen
  {//GEN-HEADEREND:event_onBerechnen
    final int   // Eingangsgrößen holen
      untergrenze = ((Number)spUntergrenze.getValue()).intValue(),
      obergrenze = ((Number)spObergrenze.getValue()).intValue();
    // Listenfeld löschen
    listenfeld.setModel(new PerfekteZahlListModel(new ArrayList<>()));
    pack();
    // Swingworker nutzen !!! (100ms-Regel)
    new PerfekteZahlenWorker(untergrenze, obergrenze).execute();
  }//GEN-LAST:event_onBerechnen

  private void onLoeschen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onLoeschen
  {//GEN-HEADEREND:event_onLoeschen
    if (JOptionPane.showConfirmDialog(this, "Wirklich löschen?",
      "Sicherheitsabfrage", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
    {
      listenfeld.setModel(new PerfekteZahlListModel(new ArrayList<>()));
      pack();
      tfRechenzeit.setValue(0L);
      tfAnzahl.setValue(0L);
    }
  }//GEN-LAST:event_onLoeschen

  private void onX()
  {
    if(JOptionPane.showConfirmDialog(this, "Wirklich löschen?",
      "Sicherheitsabfrage", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        dispose();
  }
  
  private void onBeenden(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onBeenden
  {//GEN-HEADEREND:event_onBeenden
    onX();
  }//GEN-LAST:event_onBeenden

  private void onWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_onWindowClosing
  {//GEN-HEADEREND:event_onWindowClosing
    onX();
  }//GEN-LAST:event_onWindowClosing

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(PerfekteZahlenGuiVerion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(PerfekteZahlenGuiVerion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(PerfekteZahlenGuiVerion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(PerfekteZahlenGuiVerion2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      @Override
      public void run()
      {
        new PerfekteZahlenGuiVerion2().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBeenden;
    private javax.swing.JButton btBerechnen;
    private javax.swing.JButton btLoeschen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<PerfekteZahl> listenfeld;
    private javax.swing.JPanel pBefehle;
    private javax.swing.JPanel pEinAus;
    private javax.swing.JPanel pListenfeld;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pWest;
    private javax.swing.JSpinner spObergrenze;
    private javax.swing.JSpinner spUntergrenze;
    private javax.swing.JFormattedTextField tfAnzahl;
    private javax.swing.JFormattedTextField tfRechenzeit;
    // End of variables declaration//GEN-END:variables
}
