/*
 * Copyright 2021 msgmonster project
 * 
 * Website: https://github.com/pinorobotics/msgmonster
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Java class for jrosclient
 * 
 * Generated for ROS file: std_msgs/Int8
 */

package ue01.msg;


import java.util.Objects;

import id.jrosmessages.Message;
import id.jrosmessages.MessageMetadata;
import id.jrosmessages.Array;
import id.xfunction.XJson;
import id.xfunction.Preconditions;

/**
 * Definition for std_msgs/Int8
 * 
 * <p>This was originally provided as an example message.
 * It is deprecated as of Foxy
 * It is recommended to create your own semantically meaningful message.
 * However if you would like to continue using this please use the equivalent in example_msgs.
 * 
 * ./msgmonster ros2 demo_java.std_msgs std_msgs/msg/Int8 /home/robu/work/java/uebungen/src/ue02/demo_java_python_ws/src/demo_java/
 */
@MessageMetadata(
    name = Int8Message.NAME
)
public class Int8Message implements Message {
   
   static final String NAME = "std_msgs/Int8";

   public byte data;
   
   public Int8Message withData(byte data) {
       this.data = data;
       return this;
   }
   
   @Override
   public int hashCode() {
       return Objects.hash(
           data
       );
   }
   
   @Override
   public boolean equals(Object obj) {
       if (obj instanceof Int8Message other)
           return
               data == other.data
           ;
       return false;
   }
   
   @Override
   public String toString() {
       return XJson.asString(
           "data", data
       );
   }
   
}
