/*
 * Copyright 2021 msgmonster project
 * 
 * Website: https://github.com/pinorobotics/msgmonster
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Java class for jrosclient
 * 
 * Generated for ROS file: ledctrl_interfaces/ColorValuesServiceResponse
 */

package ue01.srv;

import java.util.Objects;

import id.jrosmessages.Message;
import id.jrosmessages.MessageMetadata;
import id.jrosmessages.Array;
import id.xfunction.XJson;
import id.xfunction.Preconditions;

import id.jrosmessages.RosInterfaceType;
import java.util.Arrays;

/**
 * Definition for ledctrl_interfaces/ColorValuesServiceResponse
 */
@MessageMetadata(
    name = ColorValuesResponseMessage.NAME,
    interfaceType = RosInterfaceType.SERVICE,
    fields = { "colors", "status" }
)
public class ColorValuesResponseMessage implements Message {
   
   static final String NAME = "ledctrl_interfaces/ColorValuesServiceResponse";

   /**
    * LED-Nr. and RGBW values for each LED
    */
   public byte[] colors = new byte[0];
   
   public boolean status;
   
   public ColorValuesResponseMessage withColors(byte... colors) {
       this.colors = colors;
       return this;
   }
   
   public ColorValuesResponseMessage withStatus(boolean status) {
       this.status = status;
       return this;
   }
   
   @Override
   public int hashCode() {
       return Objects.hash(
           Arrays.hashCode(colors),
           status
       );
   }
   
   @Override
   public boolean equals(Object obj) {
       if (obj instanceof ColorValuesResponseMessage other)
           return
               Arrays.equals(colors, other.colors) &&
               status == other.status
           ;
       return false;
   }
   
   @Override
   public String toString() {
       return XJson.asString(
           "colors", colors,
           "status", status
       );
   }
   
}
