/*
 * Copyright 2021 msgmonster project
 * 
 * Website: https://github.com/pinorobotics/msgmonster
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Java class for jrosclient
 * 
 * Generated for ROS file: ledctrl_interfaces/TurnSignal
 */

package ue01.srv;

import id.jrosmessages.MessageDescriptor;
import pinorobotics.jrosservices.msgs.ServiceDefinition;

/**
 * Definition for ledctrl_interfaces/srv/TurnSignal
 */
public class TurnSignalServiceDefinition
        implements ServiceDefinition<TurnSignalRequestMessage, TurnSignalResponseMessage> {
    private static final MessageDescriptor<TurnSignalRequestMessage> REQUEST_MESSAGE_DESCRIPTOR =
            new MessageDescriptor<>(TurnSignalRequestMessage.class);
    private static final MessageDescriptor<TurnSignalResponseMessage> RESPONSE_MESSAGE_DESCRIPTOR =
            new MessageDescriptor<>(TurnSignalResponseMessage.class);

    @Override
    public MessageDescriptor<TurnSignalRequestMessage> getServiceRequestMessage() {
        return REQUEST_MESSAGE_DESCRIPTOR;
    }

    @Override
    public MessageDescriptor<TurnSignalResponseMessage> getServiceResponseMessage() {
        return RESPONSE_MESSAGE_DESCRIPTOR;
    }
}
