/*
 * Copyright 2021 msgmonster project
 * 
 * Website: https://github.com/pinorobotics/msgmonster
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Java class for jrosclient
 * 
 * Generated for ROS file: ledctrl_interfaces/TurnSignalServiceRequest
 */

package ue01.srv;

import java.util.Objects;

import id.jrosmessages.Message;
import id.jrosmessages.MessageMetadata;
import id.xfunction.XJson;

import id.jrosmessages.RosInterfaceType;
import id.jrosmessages.std_msgs.StringMessage;

/**
 * Definition for ledctrl_interfaces/TurnSignalServiceRequest
 */
@MessageMetadata(
    name = TurnSignalRequestMessage.NAME,
    interfaceType = RosInterfaceType.SERVICE,
    fields = { "cmd", "repetitions" }
)
public class TurnSignalRequestMessage implements Message {
   
   static final String NAME = "ledctrl_interfaces/TurnSignalServiceRequest";

   public StringMessage cmd = new StringMessage();
   
   public byte repetitions;
   
   public TurnSignalRequestMessage withCmd(StringMessage cmd) {
       this.cmd = cmd;
       return this;
   }
   
   public TurnSignalRequestMessage withRepetitions(byte repetitions) {
       this.repetitions = repetitions;
       return this;
   }
   
   @Override
   public int hashCode() {
       return Objects.hash(
           cmd,
           repetitions
       );
   }
   
   @Override
   public boolean equals(Object obj) {
       if (obj instanceof TurnSignalRequestMessage other)
           return
               Objects.equals(cmd, other.cmd) &&
               repetitions == other.repetitions
           ;
       return false;
   }
   
   @Override
   public String toString() {
       return XJson.asString(
           "cmd", cmd,
           "repetitions", repetitions
       );
   }
   
}
