package Lernen.Raumdiagonale.gui;

import Lernen.Raumdiagonale.calc.QuaderGanzzahligRechner;
import com.sun.jdi.connect.spi.TransportService;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author Rafael
 */
public class QuaderGanzzahligGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuaderGanzzahligGUI.class.getName());

    /**
     * Creates new form QuaderGanzzahligGUI
     */
    public QuaderGanzzahligGUI() {
        initComponents();
        guiLoeschen();
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pMain = new javax.swing.JPanel();
        pContent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        tfObergrenze = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        btBerechnen = new javax.swing.JButton();
        btLoeschen = new javax.swing.JButton();
        btBeenden = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfAnzahlLoesungen = new javax.swing.JFormattedTextField();
        tfDauer = new javax.swing.JFormattedTextField();
        pList = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        liste = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowsClosing(evt);
            }
        });

        pMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pMain.setLayout(new java.awt.GridLayout());

        pContent.setLayout(new java.awt.GridLayout(0, 1));

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8), javax.swing.BorderFactory.createTitledBorder("Obergrenze")));
        java.awt.GridBagLayout jPanel1Layout = new java.awt.GridBagLayout();
        jPanel1Layout.columnWidths = new int[] {0};
        jPanel1Layout.rowHeights = new int[] {0};
        jPanel1.setLayout(jPanel1Layout);

        tfObergrenze.setFormatterFactory(0);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(tfObergrenze, gridBagConstraints);

        pContent.add(jPanel1);

        jPanel3.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8), javax.swing.BorderFactory.createTitledBorder("Aktion")));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        jPanel3Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        jPanel3.setLayout(jPanel3Layout);

        btBerechnen.setText("Berechnen");
        btBerechnen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBerechnen(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel3.add(btBerechnen, gridBagConstraints);

        btLoeschen.setText("Löschen");
        btLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnAusgabeLoeschen(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel3.add(btLoeschen, gridBagConstraints);

        btBeenden.setText("Beenden");
        btBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OnBeenden(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel3.add(btBeenden, gridBagConstraints);

        pContent.add(jPanel3);

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8), javax.swing.BorderFactory.createTitledBorder("Ausgabe")));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
        jPanel2Layout.rowHeights = new int[] {0, 5, 0, 5, 0};
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setText("Anzahl Lösungen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Dauer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setText("ms");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel3, gridBagConstraints);

        tfAnzahlLoesungen.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel2.add(tfAnzahlLoesungen, gridBagConstraints);

        tfDauer.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel2.add(tfDauer, gridBagConstraints);

        pContent.add(jPanel2);

        pMain.add(pContent);

        pList.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8), javax.swing.BorderFactory.createTitledBorder("Liste")));
        pList.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(liste);

        pList.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pMain.add(pList);

        getContentPane().add(pMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onBerechnen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBerechnen
        btBerechnen.setEnabled(false);
        guiLoeschen();
        final int obergrenze = ((Number)tfObergrenze.getValue().intValue());
        new QuaderGanzzahligWorker(obergrenze).execute();
    }//GEN-LAST:event_onBerechnen

    private void OnAusgabeLoeschen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnAusgabeLoeschen
        if(JOptionPane.showConfirmDialog(this, "Ausgabe wirklich löschen?", "Sicherheitsabfrage",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            guiLoeschen();
        }
    }//GEN-LAST:event_OnAusgabeLoeschen

    private void OnBeenden(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OnBeenden
        guiBeenden();
    }//GEN-LAST:event_OnBeenden

    private void onWindowsClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowsClosing
        guiBeenden();
    }//GEN-LAST:event_onWindowsClosing

    private void guiLoeschen() {
        liste.setModel(new QuaderGanzzahligModel(new ArrayList<>()));
        tfAnzahlLoesungen.setValue(0);
        tfDauer.setValue(0);
    }

    private void guiBeenden() {
        if(JOptionPane.showConfirmDialog(this, "Ausgabe wirklich löschen?", "Sicherheitsabfrage",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            dispose();
        }
    }
    
    private static class QuaderGanzzahligWorker extends SwingWorker<QuaderGanzzahligRechner, Object>{
        private final int obergrenze;
        
        public QuaderGanzzahligWorker(int obergrenze) {
            this.obergrenze = obergrenze;
        }

        @Override
        protected QuaderGanzzahligRechner doInBackground() throws Exception {
            return new QuaderGanzzahligRechner(obergrenze);
        }

        @Override
        protected void done() {
            try {
                final QuaderGanzzahligRechner qgr = get();
                btBerechnen.setEnabled(true);
                tfAnzahlLoesungen.setValue(qgr.getListe().size());
                tfDauer.setValue(qgr.getMillis());
                liste.setModel(new QuaderganzzahligModel(qgr.getListe()));
                pack();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(QuaderGanzzahligGUI.this, ex.getCause().getMessage(), 
                        "Fehlermeldung", JOptionPane.ERROR_MESSAGE);
            }
        }

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuaderGanzzahligGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBeenden;
    private javax.swing.JButton btBerechnen;
    private javax.swing.JButton btLoeschen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<QuaderGanzzahlig> liste;
    private javax.swing.JPanel pContent;
    private javax.swing.JPanel pList;
    private javax.swing.JPanel pMain;
    private javax.swing.JFormattedTextField tfAnzahlLoesungen;
    private javax.swing.JFormattedTextField tfDauer;
    private javax.swing.JFormattedTextField tfObergrenze;
    // End of variables declaration//GEN-END:variables

}
