/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ue09.gui;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.plaf.ProgressBarUI;
import ue09.calc.PytTripRechner;
import ue09.data.PytTrip;

/**
 *
 * @author robu
 */
public class PytTripGui extends javax.swing.JFrame
{

  /**
   * Creates new form PytTripGui
   */
  public PytTripGui()
  {
    initComponents();
    //Listenmodel setzen (vorerst mit 0 pytagoräischen Tripeln)
    listenfeld.setModel(new PytTripListModel(new ArrayList()));
    pack();   
      
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents()
  {
    java.awt.GridBagConstraints gridBagConstraints;

    pMain = new javax.swing.JPanel();
    pSouth = new javax.swing.JPanel();
    progressBar = new javax.swing.JProgressBar();
    pWest = new javax.swing.JPanel();
    pEingabe = new javax.swing.JPanel();
    spObergrenze = new javax.swing.JSpinner();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    tfErgebnisse = new javax.swing.JFormattedTextField();
    tfDauer = new javax.swing.JFormattedTextField();
    pButtons = new javax.swing.JPanel();
    btBerechnen = new javax.swing.JButton();
    btLoeschen = new javax.swing.JButton();
    btBeenden = new javax.swing.JButton();
    pEast = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    listenfeld = new javax.swing.JList<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
    setTitle("Pythagoräische Tripel V 0.1");
    setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
    setLocationByPlatform(true);
    addWindowListener(new java.awt.event.WindowAdapter()
    {
      public void windowClosing(java.awt.event.WindowEvent evt)
      {
        onWindowClosing(evt);
      }
    });

    pMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    pMain.setLayout(new java.awt.BorderLayout());

    pSouth.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
    pSouth.setLayout(new java.awt.BorderLayout());

    progressBar.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
    progressBar.setString("Sinking");
    pSouth.add(progressBar, java.awt.BorderLayout.CENTER);

    pMain.add(pSouth, java.awt.BorderLayout.PAGE_END);

    pWest.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 8));
    pWest.setLayout(new java.awt.BorderLayout());

    pEingabe.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Ein-/Ausgabe", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DejaVu Sans", 0, 12)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10))); // NOI18N
    java.awt.GridBagLayout pEingabeLayout = new java.awt.GridBagLayout();
    pEingabeLayout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
    pEingabeLayout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0};
    pEingabe.setLayout(pEingabeLayout);

    spObergrenze.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
    spObergrenze.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
    spObergrenze.setToolTipText("");
    spObergrenze.setName(""); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.ipadx = 40;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pEingabe.add(spObergrenze, gridBagConstraints);

    jLabel1.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
    jLabel1.setText("ms");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 22;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pEingabe.add(jLabel1, gridBagConstraints);

    jLabel2.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
    jLabel2.setText("Ergebnisse");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pEingabe.add(jLabel2, gridBagConstraints);

    jLabel3.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
    jLabel3.setText("Dauer");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pEingabe.add(jLabel3, gridBagConstraints);

    jLabel4.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
    jLabel4.setText("Obergrenze");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 4;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.gridwidth = 3;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pEingabe.add(jLabel4, gridBagConstraints);

    tfErgebnisse.setColumns(20);
    tfErgebnisse.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
    tfErgebnisse.setFocusable(false);
    tfErgebnisse.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.gridwidth = 13;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pEingabe.add(tfErgebnisse, gridBagConstraints);

    tfDauer.setColumns(20);
    tfDauer.setFocusable(false);
    tfDauer.setFont(new java.awt.Font("DejaVu Sans", 0, 14)); // NOI18N
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 8;
    gridBagConstraints.gridy = 8;
    gridBagConstraints.gridwidth = 13;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
    pEingabe.add(tfDauer, gridBagConstraints);

    pWest.add(pEingabe, java.awt.BorderLayout.PAGE_START);

    pButtons.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Befehle", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DejaVu Sans", 0, 12)), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8))); // NOI18N
    java.awt.GridBagLayout pButtonsLayout = new java.awt.GridBagLayout();
    pButtonsLayout.columnWidths = new int[] {0};
    pButtonsLayout.rowHeights = new int[] {0, 5, 0, 5, 0};
    pButtons.setLayout(pButtonsLayout);

    btBerechnen.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
    btBerechnen.setText("Berechnen");
    btBerechnen.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onBerechnen(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    pButtons.add(btBerechnen, gridBagConstraints);

    btLoeschen.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
    btLoeschen.setText("Löschen");
    btLoeschen.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onLoeschen(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    pButtons.add(btLoeschen, gridBagConstraints);

    btBeenden.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
    btBeenden.setText("Beenden");
    btBeenden.addActionListener(new java.awt.event.ActionListener()
    {
      public void actionPerformed(java.awt.event.ActionEvent evt)
      {
        onBeenden(evt);
      }
    });
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    pButtons.add(btBeenden, gridBagConstraints);

    pWest.add(pButtons, java.awt.BorderLayout.CENTER);

    pMain.add(pWest, java.awt.BorderLayout.LINE_START);

    pEast.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED), "Liste der Tripel", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("DejaVu Sans", 0, 12)), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8))); // NOI18N
    pEast.setLayout(new java.awt.BorderLayout());

    listenfeld.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
    jScrollPane2.setViewportView(listenfeld);

    pEast.add(jScrollPane2, java.awt.BorderLayout.CENTER);

    pMain.add(pEast, java.awt.BorderLayout.CENTER);

    getContentPane().add(pMain, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents
  
  private void onX()
  {
    if(JOptionPane.showConfirmDialog(this, "Wirklich beenden?", "Sicherheitsabfrage", JOptionPane.YES_NO_OPTION) 
            == JOptionPane.YES_OPTION)
          dispose();
  }
  
  private void onBeenden(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onBeenden
  {//GEN-HEADEREND:event_onBeenden
    onX();
  }//GEN-LAST:event_onBeenden

  private void onWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_onWindowClosing
  {//GEN-HEADEREND:event_onWindowClosing
    onX();
  }//GEN-LAST:event_onWindowClosing

  private void onLoeschen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onLoeschen
  {//GEN-HEADEREND:event_onLoeschen
    // listenfeld löschen 
    listenfeld.setModel(new PytTripListModel(new ArrayList<>()));
  }//GEN-LAST:event_onLoeschen

  // SwingWorker als "innere Klasse"
  private class PytTripsWorker extends SwingWorker<PytTripRechner, Object> 
  {
    private final int obergrenze;
    
    public PytTripsWorker(int obergrenze)
    {
      this.obergrenze = obergrenze;
    }
    
    @Override
    protected PytTripRechner doInBackground() throws Exception
    {
      // Im Hintergrund (im worker thread) rechnen und Ergebnis rückliefern
      return new PytTripRechner(obergrenze);
    }
    
    @Override
    protected void done()
    {
      try
      {
        progressBar.setIndeterminate(false);
        progressBar.setStringPainted(false);
        btBerechnen.setEnabled(true);
        // Ergebnis abholen
        final PytTripRechner rechner = get();
        // Ausgangsgrößen abholen
        final long millis = rechner.getMillis();
        final List<PytTrip> pytTrips = rechner.getPytTrips();
        //Ausgangsgrößen
        tfDauer.setValue(millis);
        tfErgebnisse.setValue(pytTrips.size());
        listenfeld.setModel(new PytTripListModel(pytTrips));
        pack();
      }
      catch (InterruptedException ignore) { }
      catch (ExecutionException ex)
      {
        JOptionPane.showMessageDialog(PytTripGui.this, ex.getCause().getMessage(),
                "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
      }
    }
    
  }
    
  
  
  private void onBerechnen(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onBerechnen
  {//GEN-HEADEREND:event_onBerechnen
    try
    {
      //Eingangsgröße holen
      final int obergrenze = ((Number)spObergrenze.getValue()).intValue();
      // Listenfeld löschen
      listenfeld.setModel(new PytTripListModel(new ArrayList<>()));
      progressBar.setIndeterminate(true);
      progressBar.setStringPainted(true);
      btBerechnen.setEnabled(false);
      // Swingworker erzeugen und starten
      new PytTripsWorker(obergrenze).execute();
      
      /*
      // Rechnen: Rechnerklasse bauen
      final PytTripRechner rechner = new PytTripRechner(obergrenze);
      // Ausgangsgrößen abholen
      final long millis = rechner.getMillis();
      final List<PytTrip> pytTrips = rechner.getPytTrips();
      //Ausgangsgrößen
      tfDauer.setValue(millis);
      tfErgebnisse.setValue(pytTrips.size());
      listenfeld.setModel(new PytTripListModel(pytTrips));
      pack();
      */
    }
    catch (Exception ex)
    {
      JOptionPane.showMessageDialog(this, ex.getMessage(),
          "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
    }
    
  }//GEN-LAST:event_onBerechnen

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try
    {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
      {
        if ("Nimbus".equals(info.getName()))
        {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    }
    catch (ClassNotFoundException ex)
    {
      java.util.logging.Logger.getLogger(PytTripGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (InstantiationException ex)
    {
      java.util.logging.Logger.getLogger(PytTripGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (IllegalAccessException ex)
    {
      java.util.logging.Logger.getLogger(PytTripGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    catch (javax.swing.UnsupportedLookAndFeelException ex)
    {
      java.util.logging.Logger.getLogger(PytTripGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable()
    {
      public void run()
      {
        new PytTripGui().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btBeenden;
  private javax.swing.JButton btBerechnen;
  private javax.swing.JButton btLoeschen;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JList<PytTrip> listenfeld;
  private javax.swing.JPanel pButtons;
  private javax.swing.JPanel pEast;
  private javax.swing.JPanel pEingabe;
  private javax.swing.JPanel pMain;
  private javax.swing.JPanel pSouth;
  private javax.swing.JPanel pWest;
  private javax.swing.JProgressBar progressBar;
  private javax.swing.JSpinner spObergrenze;
  private javax.swing.JFormattedTextField tfDauer;
  private javax.swing.JFormattedTextField tfErgebnisse;
  // End of variables declaration//GEN-END:variables
}
