/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ue01.gui;

import ue01.data.RobotCtrlROS;

/**
 *
 * @author robu
 */
public class EmptyPanel extends javax.swing.JPanel
{

    private final RobotCtrlROS nodeRobotCtrl;
    private final RobotCtrlGUI parent;

    public EmptyPanel(RobotCtrlGUI parent, RobotCtrlROS nodeRobotCtrl)
    {
        this.nodeRobotCtrl = nodeRobotCtrl;
        this.parent = parent;
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pMain = new javax.swing.JPanel();
        pSouth = new javax.swing.JPanel();
        btnSaveParam = new javax.swing.JButton();
        btnLoadParam = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(800, 400));
        setMinimumSize(new java.awt.Dimension(700, 300));
        setPreferredSize(new java.awt.Dimension(800, 400));
        setLayout(new java.awt.BorderLayout());

        pMain.setMaximumSize(new java.awt.Dimension(0, 0));
        pMain.setMinimumSize(new java.awt.Dimension(0, 0));
        pMain.setPreferredSize(new java.awt.Dimension(617, 400));
        pMain.setLayout(new java.awt.BorderLayout());
        add(pMain, java.awt.BorderLayout.CENTER);

        pSouth.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 4, 5));

        btnSaveParam.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnSaveParam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/write-bot_48x48.png"))); // NOI18N
        btnSaveParam.setToolTipText("Einstellungen auf dem Roboter speichern");
        btnSaveParam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onSaveParameter(evt);
            }
        });
        pSouth.add(btnSaveParam);

        btnLoadParam.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnLoadParam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/read-bot_48x48.png"))); // NOI18N
        btnLoadParam.setToolTipText("Einstellungen vom Roboter laden");
        btnLoadParam.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onLoadParameter(evt);
            }
        });
        pSouth.add(btnLoadParam);

        btnClose.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ue02/icons/logout_48x48.png"))); // NOI18N
        btnClose.setToolTipText("Beenden");
        btnClose.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                onClose(evt);
            }
        });
        pSouth.add(btnClose);

        add(pSouth, java.awt.BorderLayout.SOUTH);

        getAccessibleContext().setAccessibleName("");
    }// </editor-fold>//GEN-END:initComponents

    private void onClose(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onClose
    {//GEN-HEADEREND:event_onClose
        this.parent.closeGUI();
    }//GEN-LAST:event_onClose

    
    private void onSaveParameter(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onSaveParameter
    {//GEN-HEADEREND:event_onSaveParameter

    }//GEN-LAST:event_onSaveParameter

    private void onLoadParameter(java.awt.event.ActionEvent evt)//GEN-FIRST:event_onLoadParameter
    {//GEN-HEADEREND:event_onLoadParameter

        
    }//GEN-LAST:event_onLoadParameter


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnLoadParam;
    private javax.swing.JButton btnSaveParam;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pSouth;
    // End of variables declaration//GEN-END:variables
}
