/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ue08.gui;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import ue08.calc.StatistikRechner;

/**
 *
 * @author robot
 */
public class StatistikGui extends javax.swing.JFrame {

    // Collection für beliebig viele Double-Werte
    private final List<Double> liste = new ArrayList<>(); 
    
    /**
     * Creates new form StatistikGui
     */
    public StatistikGui() {
        initComponents();
        listenfeld.setModel(new DoubleListModel(liste));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pMain = new javax.swing.JPanel();
        pSouth = new javax.swing.JPanel();
        pButtons = new javax.swing.JPanel();
        btHinzufuegen = new javax.swing.JButton();
        btLoeschen = new javax.swing.JButton();
        btAllesLoeschen = new javax.swing.JButton();
        btBerechnen = new javax.swing.JButton();
        btBeenden = new javax.swing.JButton();
        pEast = new javax.swing.JPanel();
        pEingabe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfZahl = new javax.swing.JFormattedTextField();
        pAusgabe = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfDurchschnitt = new javax.swing.JFormattedTextField();
        tfStdAbw = new javax.swing.JFormattedTextField();
        pCenter = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listenfeld = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Statistische berechnungnen V0.1");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                onWindowClosing(evt);
            }
        });

        pMain.setBorder(javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8));
        pMain.setLayout(new java.awt.BorderLayout(8, 8));

        pButtons.setLayout(new java.awt.GridLayout(1, 0, 8, 0));

        btHinzufuegen.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        btHinzufuegen.setText("Hinzufügen");
        btHinzufuegen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onHinzufuegen(evt);
            }
        });
        pButtons.add(btHinzufuegen);

        btLoeschen.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        btLoeschen.setText("Löschen");
        btLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onLoeschen(evt);
            }
        });
        pButtons.add(btLoeschen);

        btAllesLoeschen.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        btAllesLoeschen.setText("Alles löschen");
        btAllesLoeschen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onAllesLoeschen(evt);
            }
        });
        pButtons.add(btAllesLoeschen);

        btBerechnen.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        btBerechnen.setText("Berechnen");
        btBerechnen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBerechnen(evt);
            }
        });
        pButtons.add(btBerechnen);

        btBeenden.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        btBeenden.setText("Beenden");
        btBeenden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onBeenden(evt);
            }
        });
        pButtons.add(btBeenden);

        pSouth.add(pButtons);

        pMain.add(pSouth, java.awt.BorderLayout.PAGE_END);

        pEast.setLayout(new java.awt.BorderLayout());

        pEingabe.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eingabe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)));
        pEingabe.setLayout(new java.awt.BorderLayout(4, 0));

        jLabel1.setText("Zahl");
        pEingabe.add(jLabel1, java.awt.BorderLayout.WEST);

        tfZahl.setColumns(10);
        tfZahl.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        tfZahl.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        pEingabe.add(tfZahl, java.awt.BorderLayout.CENTER);

        pEast.add(pEingabe, java.awt.BorderLayout.NORTH);

        pAusgabe.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ausgabe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)));
        java.awt.GridBagLayout pAusgabeLayout = new java.awt.GridBagLayout();
        pAusgabeLayout.columnWidths = new int[] {0, 5, 0};
        pAusgabeLayout.rowHeights = new int[] {0, 5, 0};
        pAusgabe.setLayout(pAusgabeLayout);

        jLabel2.setText("Durchschnitt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pAusgabe.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Standartabweichung");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        pAusgabe.add(jLabel3, gridBagConstraints);

        tfDurchschnitt.setEditable(false);
        tfDurchschnitt.setColumns(10);
        tfDurchschnitt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        tfDurchschnitt.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        pAusgabe.add(tfDurchschnitt, gridBagConstraints);

        tfStdAbw.setEditable(false);
        tfStdAbw.setColumns(10);
        tfStdAbw.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        tfStdAbw.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        pAusgabe.add(tfStdAbw, gridBagConstraints);

        pEast.add(pAusgabe, java.awt.BorderLayout.SOUTH);

        pMain.add(pEast, java.awt.BorderLayout.LINE_END);

        pCenter.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(null, "Liste der Zahlen", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP), javax.swing.BorderFactory.createEmptyBorder(8, 8, 8, 8)));
        pCenter.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(listenfeld);

        pCenter.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pMain.add(pCenter, java.awt.BorderLayout.CENTER);

        getContentPane().add(pMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void onBeenden(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBeenden
        onX();
    }//GEN-LAST:event_onBeenden

    private void onHinzufuegen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onHinzufuegen
        // Schritt 1: Eingegebene Zahlen aus formatiertem Feld auslesen
        final double zahl = ((Number)tfZahl.getValue()).doubleValue();
        // Schritt 2: Zahl an die Liste anfügen
        liste.add(zahl);
        // Schritt 3: Listenfeld aktualisieren (neues ListModel)
        listenfeld.setModel(new DoubleListModel(liste));
    }//GEN-LAST:event_onHinzufuegen

    private void onBerechnen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onBerechnen
        try {
            //Schritt 1: Rechnerobjekt bauen
            final StatistikRechner rechner = new StatistikRechner(liste);
            //Schritt 2: Ergebnisse abholen und in die formatierten Felder ausgeben
            tfDurchschnitt.setValue(rechner.getDurchschnitt()); //Durchschnitt ausgeben
            tfStdAbw.setValue(rechner.getStdAbw());
        } 
        catch(Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(),
                "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_onBerechnen

    private void onLoeschen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onLoeschen
        // *** Variante 1: EINEN Eintrag löschen ***
        /*
        final int selectedIndex = listenfeld.getSelectedIndex(); //Finde selektrierten Index
        if(selectedIndex<0) { // Wenn nichts selektiert ist 
            JOptionPane.showMessageDialog(this, 
                "Bitte erst mindestens einen Eintrag selektieren",
                "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
        }
        else {
            if(JOptionPane.showConfirmDialog(this, 
                "Selektierten Eintrag wirklich löschen?",
                "Sicherheitsabfrage", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                
                liste.remove(selectedIndex); // Aus der Liste löschen
                // Listenfeld aktualisieren (neues Model)
                listenfeld.setModel(new DoubleListModel(liste));
            }
        }
        */
        
        // *** Variante 2: ALLE selektierten Einträge löschen ***
        final int[] sel = listenfeld.getSelectedIndices();
        if(sel.length < 1) {// Wenn nichts selektiert ist 
            JOptionPane.showMessageDialog(this, 
                "Bitte erst mindestens einen Eintrag selektieren",
                "Fehler aufgetreten", JOptionPane.ERROR_MESSAGE);
        }
        else {
            if(JOptionPane.showConfirmDialog(this, 
                String.format("Wirklich %d Selektierte Eintraeg loeschen?", sel.length),
                "Sicherheitsabfrage", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
                
                for(int i=sel.length-1;i>=0;i--) {
                    liste.remove(sel[i]); //Doppelte INdizierung !!!!!
                    listenfeld.setModel(new DoubleListModel(liste)); //Model aktualisieren
                }
            }
        }
    }//GEN-LAST:event_onLoeschen

    private void onWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_onWindowClosing
        onX();
    }//GEN-LAST:event_onWindowClosing

    private void onAllesLoeschen(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onAllesLoeschen
        //listenfeld loeschen
        liste.clear(); //loeschen der Inhalte
        listenfeld.setModel(new DoubleListModel(liste)); //Listenfeld aktualisieren
        //Alle formatierten Felder mit Null beschreiben
        tfZahl.setValue(0.0);
        tfDurchschnitt.setValue(0.0);
        tfStdAbw.setValue(0.0);
    }//GEN-LAST:event_onAllesLoeschen
    
    private void onX() {
        if(JOptionPane.showConfirmDialog(this, "Wirklich beenden?",
                "Sicherheitsabfrage", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
            dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StatistikGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StatistikGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StatistikGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StatistikGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StatistikGui().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAllesLoeschen;
    private javax.swing.JButton btBeenden;
    private javax.swing.JButton btBerechnen;
    private javax.swing.JButton btHinzufuegen;
    private javax.swing.JButton btLoeschen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<Double> listenfeld;
    private javax.swing.JPanel pAusgabe;
    private javax.swing.JPanel pButtons;
    private javax.swing.JPanel pCenter;
    private javax.swing.JPanel pEast;
    private javax.swing.JPanel pEingabe;
    private javax.swing.JPanel pMain;
    private javax.swing.JPanel pSouth;
    private javax.swing.JFormattedTextField tfDurchschnitt;
    private javax.swing.JFormattedTextField tfStdAbw;
    private javax.swing.JFormattedTextField tfZahl;
    // End of variables declaration//GEN-END:variables
}
