/*
 * Copyright 2021 msgmonster project
 * 
 * Website: https://github.com/pinorobotics/msgmonster
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * msgmonster autogenerated Java class for jrosclient
 * 
 * Generated for ROS file: ledctrl_interfaces/CameraCmdServiceRequest
 */

package ue02.ros.srv;

import java.util.Objects;

import id.jrosmessages.Message;
import id.jrosmessages.MessageMetadata;
import id.jrosmessages.Array;
import id.xfunction.XJson;
import id.xfunction.Preconditions;

import id.jrosmessages.RosInterfaceType;
import id.jrosmessages.std_msgs.StringMessage;
import java.util.Arrays;

/**
 * Definition for ledctrl_interfaces/CameraCmdServiceRequest
 */
@MessageMetadata(
    name = CameraCmdRequestMessage.NAME,
    interfaceType = RosInterfaceType.SERVICE,
    fields = { "cmd", "side", "color_on", "color_off", "duration_on", "duration_off", "repetitions" }
)
public class CameraCmdRequestMessage implements Message {
   
   static final String NAME = "ledctrl_interfaces/CameraCmdServiceRequest";

   /**
    * turn signal, detection  indication, warn-signal,
    */
   public StringMessage cmd = new StringMessage();
   
   /**
    * left, right, both
    */
   public byte side;
   
   /**
    * RGBW values
    */
   public byte[] color_on = new byte[0];
   
   /**
    * RGBW values
    */
   public byte[] color_off = new byte[0];
   
   /**
    * duration in seconds
    */
   public float duration_on;
   
   /**
    * duration in seconds
    */
   public float duration_off;
   
   public byte repetitions;
   
   public CameraCmdRequestMessage withCmd(StringMessage cmd) {
       this.cmd = cmd;
       return this;
   }
   
   public CameraCmdRequestMessage withSide(byte side) {
       this.side = side;
       return this;
   }
   
   public CameraCmdRequestMessage withColorOn(byte... color_on) {
       this.color_on = color_on;
       return this;
   }
   
   public CameraCmdRequestMessage withColorOff(byte... color_off) {
       this.color_off = color_off;
       return this;
   }
   
   public CameraCmdRequestMessage withDurationOn(float duration_on) {
       this.duration_on = duration_on;
       return this;
   }
   
   public CameraCmdRequestMessage withDurationOff(float duration_off) {
       this.duration_off = duration_off;
       return this;
   }
   
   public CameraCmdRequestMessage withRepetitions(byte repetitions) {
       this.repetitions = repetitions;
       return this;
   }
   
   @Override
   public int hashCode() {
       return Objects.hash(
           cmd,
           side,
           Arrays.hashCode(color_on),
           Arrays.hashCode(color_off),
           duration_on,
           duration_off,
           repetitions
       );
   }
   
   @Override
   public boolean equals(Object obj) {
       if (obj instanceof CameraCmdRequestMessage other)
           return
               Objects.equals(cmd, other.cmd) &&
               side == other.side &&
               Arrays.equals(color_on, other.color_on) &&
               Arrays.equals(color_off, other.color_off) &&
               duration_on == other.duration_on &&
               duration_off == other.duration_off &&
               repetitions == other.repetitions
           ;
       return false;
   }
   
   @Override
   public String toString() {
       return XJson.asString(
           "cmd", cmd,
           "side", side,
           "color_on", color_on,
           "color_off", color_off,
           "duration_on", duration_on,
           "duration_off", duration_off,
           "repetitions", repetitions
       );
   }
   
}
